### ISSUE TITLE
Update deps tesla to 1.0.0 and libcluster to 3.0

### ISSUE THREAD

**Issue by seantanly** [kyleaa/libcluster_ec2#11]
Related to https://github.com/bitwalker/libcluster/issues/74

`libcluster` is currently `3.0.2` though it is not released on hex.pm yet. There should be a new release soon for compatibility with Erlang OTP 21.0.

Also `tesla` `1.0.0` is released.

https://github.com/teamon/tesla/wiki/0.x-to-1.0-Migration-Guide

Can we have the `mix.exs` updated to reflect that?
E.g.
```
{:tesla, "~> 1.0.0"},
{:libcluster, "~> 2.0 or ~> 3.0"},
```

Thank you!

**Comment by seantanly** [comment]
Please do not merge this PR yet. Looking at the changes to `libcluster` version 3.0 is not  compatible without change.

https://github.com/bitwalker/libcluster/blob/master/lib/strategy/epmd.ex#L20

The opts being passed in is a List of `%State{}` in version 3.0.

**Comment by seantanly** [comment]
Can we have version `0.4.0` released onto hex? :)

**Comment by kyleaa** [comment]
done, sorry about that!

**Comment by seantanly** [comment]
@kyleaa Thank you again! :D
