### ISSUE TITLE
Multiple failures when cluster is coming online

### ISSUE THREAD

**Issue by mgwidmann** [kyleaa/libcluster_ec2#19]
As all the nodes boot up in the cluster I am seeing the following show up in my logs:

```
01:58:26.866 [error] Supervisor 'Elixir.MyApplication.ClusterSupervisor' had child 'Elixir.ClusterEC2.Strategy.Tags' started with 'Elixir.ClusterEC2.Strategy.Tags':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [{ec2_tagname,<<"MyApplication">>},...],...}]) at <0.2182.0> exit with reason {fatal,{unexpected_end,{file,file_name_unknown},{line,2136},{col,48}}} in context child_terminated
```

My nodes are compiling erlang from source once the EC2 instance is online, so there is a good 5 minutes or so which the machine is up but there's nothing to connect to.

Shouldn't `libcluster_ec2` just ignore errors like this?

**Comment by kyleaa** [comment]
It sounds like this error could be thrown by sweetxml if invalid input is provided, but that would imply the ec2 metadata API was not responding correctly. Looking at your fork it seems like you're pursuing that route. Is this reliably occurring in your application/environment? I'd need to be able to reproduce it to help investigate.
