### ISSUE TITLE
Sweet XML error

### ISSUE THREAD

**Issue by broodfusion** [kyleaa/libcluster_ec2#22]
![image](https://user-images.githubusercontent.com/11618564/75569602-47437f00-5a0a-11ea-9df8-55437d7938ad.png)

Hi @kyleaa , we're seeing this error in our production environment. Any idea what might be going on?
Thanks!

**Comment by kyleaa** [comment]
Per our Slack discussion, it appears there's invalid XML coming back from AWS (in this case, an empty string. This is similar to #19 and it would seem there needs to be better error recovery in this block.
