### ISSUE TITLE
Rarely fails to get Instance Metadata

### ISSUE THREAD

**Issue by h3poteto** [kyleaa/libcluster_ec2#36]
Most of the time it works very well, thank you for your maintenance.

Rarely fails to get Instance Metadata, and as a result, the VM shuts down.
I have two patterns.

The first pattern is
```
 22:58:38.274 [error] GenServer #PID<0.2279.0> terminating
 ** (RuntimeError) Instance Meta Error: {:error, %{reason: :econnrefused}}
 You tried to access the AWS EC2 instance meta, but it could not be reached.
 This happens most often when trying to access it from your local computer,
 which happens when environment variables are not set correctly prompting
 ExAws to fallback to the Instance Meta.
 Please check your key config and make sure they're configured correctly:
 For Example:
 
 ExAws.Config.new(:s3)
 ExAws.Config.new(:dynamodb)

     (ex_aws 2.5.1) lib/ex_aws/instance_meta.ex:27: ExAws.InstanceMeta.request/3
     (libcluster_ec2 0.8.1) lib/strategy/tags.ex:124: ClusterEC2.Strategy.Tags.get_nodes/1
     (libcluster_ec2 0.8.1) lib/strategy/tags.ex:85: ClusterEC2.Strategy.Tags.load/1
     (libcluster_ec2 0.8.1) lib/strategy/tags.ex:77: ClusterEC2.Strategy.Tags.handle_info/2
     (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
     (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
     (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
 Last message: :load
```

And second pattern is
```
05:44:04.090 [error] GenServer #PID<0.2280.0> terminating
** (RuntimeError) Instance Meta Error: HTTP response status code 503
Please check AWS EC2 IAM role.
(ex_aws 2.5.3) lib/ex_aws/instance_meta.ex:51: ExAws.InstanceMeta.retry_or_raise/4
(libcluster_ec2 0.8.1) lib/strategy/tags.ex:124: ClusterEC2.Strategy.Tags.get_nodes/1
(libcluster_ec2 0.8.1) lib/strategy/tags.ex:85: ClusterEC2.Strategy.Tags.load/1
(libcluster_ec2 0.8.1) lib/strategy/tags.ex:77: ClusterEC2.Strategy.Tags.handle_info/2
(stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
(stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
(stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :load
```

Both of them failed to get `instance_id` from Instance Metadata Service: https://github.com/kyleaa/libcluster_ec2/blob/c50d97b69c03248f6857774522b0fa3012418c34/lib/strategy/tags.ex#L124

Probably, my configuration is correct because usually works normally.
```
  config :ex_aws,
    access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
    secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
    debug_requests: true,
    region: {:system, "AWS_REGION"}

  config :libcluster,
    topologies: [
      example: [
        strategy: ClusterEC2.Strategy.Tags,
        config: [
          ec2_tagname: "exaws/cluster_name",
          ec2_tagvalue: System.fetch_env!("CLUSTER_NAME"),
          app_prefix: "my_app",
          ip_type: :private,
          show_debug: false
        ]
      ]
    ]
```

---
ex_aws retry requests to normal AWS APIs, but it doesn't retry requests to IMDS. I think temporary failures should be kept at the warning level and should not cause a RuntimeError, but what do you think?

**Comment by sjmueller** [comment]
Our api is getting killed by this exact issue, we can go days or weeks without a problem, but then boom our entire api is toast --  we enter an unrecoverable state and our EC2 instances must be rebooted. Agree with @h3poteto that these temporary failures should just be warnings!

<img width="1033" alt="image" src="https://github.com/kyleaa/libcluster_ec2/assets/29085/5ce0d38d-63c3-45bf-a9de-aea8f4baf649">

<img width="865" alt="image" src="https://github.com/kyleaa/libcluster_ec2/assets/29085/96e6d872-2ca3-43e0-891f-135d5e2e5878">

**Comment by kyleaa** [comment]
Can you try out the new release 0.8.2? I moved the calls to fetch metadata to only be at startup, given that the values needed never change.

**Comment by h3poteto** [comment]
Thank you!
After I update 0.8.2, the error no longer happens.
