### ISSUE TITLE
README hint to ex_aws configuration

### ISSUE THREAD

**Issue by cybrox** [kyleaa/libcluster_ec2#7]
While it is technically obvious, that the `ex_aws` dependency needs to be configured first, I did completely miss it on my first attempt of using this strategy, since I did note use `ex_aws` in the application itself before.

Due to the way `ex_aws` behaves, it does not resort to using the instance role when nothing is configured at all, which causes this strategy to just fail silently.

Thus, I would suggesst adding a hint to the [access key configuration](https://github.com/ex-aws/ex_aws#aws-key-configuration) of the `ex_aws` dependency to this repository's README.

**Comment by kyleaa** [comment]
The linked docs show that the default resolver order does hit instance metadata by default with no configuration - I've never had to set that up before. I'll stand up and EC2 and see if I can replicate your issue.

**Comment by cybrox** [comment]
Sorry for the late response, I tested this again and it indeed seems that the `ex_aws` docs are right. I assume I forgot to properly assign an instance profile while testing the first time but did not notice because our auto-setup also configures the aws-cli for certain readonly actions, which in turn created useable credentials for all other AWS interactions.

False alarm then, sorry, though I would probably mention `ex_aws` for convenience but this is really a minor cosmetic detail. Not like it'd be hard to figure out by checking hex.pm or the mixfile.
> This is an EC2 clustering strategy for  [libcluster](https://hexdocs.pm/libcluster/) using [ex_aws](https://hexdocs.pm/ex_aws/ExAws.html)

**Comment by kyleaa** [comment]
No problem! Glad it worked out for you. I've added some additional instructions in d4163b7806ea070c8c8b00edaa5685f71323c6ae
