### ISSUE TITLE
Please Upgrade to ex_aws ~> 2.0

### ISSUE THREAD

**Issue by edescourtis** [kyleaa/libcluster_ec2#8]
I am running into conflicts with ex_aws trying to use the latest ex_aws_dynamo.

Failed to use "ex_aws" (versions 2.0.0 to 2.0.2) because
  apps/sms_routing/mix.exs requires ~> 2.0
  libcluster_ec2 (version 0.2.1) requires ~> 1.1

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
      {:ex_aws,                                                                              "~> 2.0"                   },
      {:ex_aws_dynamo,                                                               "~> 2.0"                   },

**Comment by kyleaa** [comment]
Released to hex.pm as 0.3.0
